### ISSUE TITLE
Comparative Studies of the Gut Microbiota in the Offspring of Mothers With and Without Gestational Diabetes

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#470] opened 2024-08-09 13:15 UTC
Comparative Studies of the Gut Microbiota in the Offspring of Mothers With and Without Gestational Diabetes - Mie Korslund Wiinblad Crusell – Front Cell Infect Microbiol.

https://www.frontiersin.org/journals/cellular-and-infection-microbiology/articles/10.3389/fcimb.2020.536282/full

**Comment by AishatBolarinwa** [comment] 2024-10-03 21:13
I'd like to be assigned to this paper please.
Thank you

**Comment by AishatBolarinwa** [comment] 2024-10-09 15:33
Greetings.
This paper is ready for review please.

https://bugsigdb.org/Study_1114
https://bugsigdb.org/Study_1114/Experiment_1
https://bugsigdb.org/Study_1114/Experiment_1/Signature_1
https://bugsigdb.org/Study_1114/Experiment_1/Signature_2
https://bugsigdb.org/Study_1114/Experiment_2
https://bugsigdb.org/Study_1114/Experiment_2/Signature_1
https://bugsigdb.org/Study_1114/Experiment_2/Signature_2

Thank you.

**Comment by Folakunmi21** [comment] 2024-11-05 23:16
hello @AishatBolarinwa Here is the result of your curation:

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0
3. Entered all relevant experiments and no irrelevant experiments (1 point): 0.5
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 0
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point):1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 2
10. Identified correct statistical test (1 point): 0
11. Identified MHT correction (1 point): 0
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 0.5
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 2
19. Correct use of NCBI taxonomy (2 points): 2

Total (maximum 23 points): 16

Here are the corrections to be made:
1. This is a cross-sectional observational study. 
2. Experiments 1 and 2 are from lefse and should have no MHT. 
3. There were also no confounders adjusted for the results in experiments 1 and 2.
4.  Please include this as the antibiotic exclusion; “mothers had not received antibiotic treatment within a period of 2 months before the date for the OGTT test”. 
5. “Healthy control” and “gestational diabetes mellitus” are poor representations of the compared groups. Also, please correct the definitions and the alpha diversity measurements for experiment 2 (unchanged for all measurements when comparing GDM and Non-GDM at 9 months according to figure 2 ). 
6. Datasheet 2 has additional curatable data. I'd advice that you present this to Chloe during the meeting on Thursday to confirm if you are to curate an experiment for each confounder adjusted for. You should also confirm what padj value you should use for the new experiments since FDR was carried out at 5% and 10%

@SvetlanaUP graded

**Comment by AleruDivine** [comment] 2024-11-06 01:58
@AishatBolarinwa I'd love to collaborate with you to make these corrections if that's okay with you.
Thank you so much!

**Comment by AleruDivine** [comment] 2024-11-06 08:49
Thank you @SvetlanaUP

**Comment by AishatBolarinwa** [comment] 2024-11-06 09:06
Thank you for the feedback @Folakunmi21 

Happy to work with you @AleruDivine

**Comment by AishatBolarinwa** [comment] 2024-11-15 13:12
Greetings,
@AleruDivine and I have rounded up with the corrections and the study is ready for a second review.
Thank you.

https://bugsigdb.org/Study_1114
@SvetlanaUP @Folakunmi21

**Comment by Folakunmi21** [comment] 2024-11-15 15:09
Hi @AishatBolarinwa @AishatBolarinwa What did Chloe say about datasheet 2?

**Comment by AleruDivine** [comment] 2024-11-15 15:13
@Folakunmi21 Office hours didn’t hold last week but the question was sent to @SvetlanaUP and she confirmed to curate an experiment for each confounder adjusted for. 

“ https://community-bioc.slack.com/archives/C04RATV9VCY/p1730996282503409?thread_ts=1730988400.486679&channel=C04RATV9VCY&message_ts=1730996282.503409”

The results are actually in data sheet 1.

**Comment by AishatBolarinwa** [comment] 2024-11-19 15:59
Thank you very much for the feedback @Folakunmi21 
We will effect the corrections and revert to you as soon as possible.

**Comment by AleruDivine** [comment] 2024-11-19 21:49
Thank you so much for the review and the detailed feedback @Folakunmi21 🙏

**Comment by AishatBolarinwa** [comment] 2024-11-21 20:28
Greetings 
The study is ready for a second review please.
Thank you
@SvetlanaUP @Folakunmi21

**Comment by Folakunmi21** [comment] 2024-11-25 11:00
@AleruDivine @AishatBolarinwa  Experiments 4, 6, 8, 10, 11 are missing alpha diversity

**Closed** 2024-11-25 16:17 UTC
Labels: second contribution, paper to curate, assigned, reviewed, outreachy dec2024

**Comment by AleruDivine** [comment] 2024-11-25 17:29
Thank you for your patience 🙏 @Folakunmi21 @SvetlanaUP
