### ISSUE TITLE
Dysbiosis of gut microbiota in a selected population of Parkinson's patients

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#215] opened 2024-03-07 12:50 UTC
Dysbiosis of gut microbiota in a selected population of Parkinson's patients - Pietrucci et al. - Parkinsonism & Related Disorders
https://pubmed.ncbi.nlm.nih.gov/31174953/

**Comment by Tiwalade0002** [comment] 2024-03-07 23:37
Hello @SvetlanaUP, please assign this to me.

**Comment by Marhiposa** [comment] 2024-03-08 02:08
Hello, @Omabekee @SvetlanaUP  My name is Mariam, and I just finished my first task. Please, can I be assigned to this?

**Comment by SvetlanaUP** [comment] 2024-03-08 10:35
Assigned to [Tiwalade0002](https://github.com/Tiwalade0002)

**Comment by Tiwalade0002** [comment] 2024-03-09 21:57
@SvetlanaUP @Omabekee @Marhiposa I just completed my contribution. I would appreciate your review of my curation.

**Comment by cmirzayi** [comment] 2024-04-04 19:46
| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 | 0 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 1 |
| 10 | Identified correct statistical test | 1 | 0 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 0 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 0 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 0 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 1 |
| 17 | Abundance direction correctly selected | 1 | 0 |
| 18 | Members of Signatures identified correctly | 2 | 1 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 13 |

- There are two experiments present in this study: PD vs. HC and PD vs. HC with patients on COMT inhibitors excluded.
- V3-V4 region was sequenced but missing from experiment 1
- Statistical test was a linear model
- No matching was done. They controlled for confounders in their GLMs
- No sig. differences in diversity were found.
- Missing decreased signature for signature 1
- Lachnospiraceae incorrectly curated as increased when it is decreased

**Comment by fiddyhamma** [comment] 2024-04-10 06:57
Hello @cmirzayi @SvetlanaUP 
It seems the corrections made have not yet been effected on the study, can I go ahead and make these corrections?

**Comment by SvetlanaUP** [comment] 2024-04-10 07:25
@fiddyhamma yes please :) also make notes here what and how you correct it. Thank you!

**Comment by fiddyhamma** [comment] 2024-04-10 07:31
Noted, thank you @SvetlanaUP

**Comment by fiddyhamma** [comment] 2024-04-12 09:53
Hello @SvetlanaUP 
I'm unable to access the full article online, can you help me please?

**Comment by SvetlanaUP** [comment] 2024-04-12 09:57
[1-s2.0-S1353802019302640-main.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14957172/1-s2.0-S1353802019302640-main.pdf)
[1-s2.0-S1353802019302640-mmc1.docx](https://github.com/waldronlab/BugSigDBcuration/files/14957179/1-s2.0-S1353802019302640-mmc1.docx)

**Comment by fiddyhamma** [comment] 2024-04-12 10:04
Thank you

**Comment by fiddyhamma** [comment] 2024-04-12 13:18
Hello @SvetlanaUP 
I made these changes to this study;
1. Added concise definitions to group 1
2. Curated Suppl table S7 which showed differentially abundant genera
3. I curated Lachnospiraceae as decreased in both experiments (1&2)
4. I removed matched on, lda score of 3 as I didn't find this in the study
5. I changed the statistical test to linear regression and Wilcoxon and set the alpha diversity as unchanged 
6. Completed experiment 2 with both increased and decreased taxas

**Comment by Scholarpat** [comment] 2024-07-08 13:12
Hi @SvetlanaUP,

Here are the changes I made to this curation:

- Corrected a misspelling in Group 1 name for both experiments.
- Changed Group 1 definition in experiment 2.
- Changed the signature source from 'Table 1A, Figure 1, Suppl table S7A, and text' to just 'Supplementary Table S7A and S7B' for experiments 1 and 2 respectively. This is because the supplementary table is easier to interpret and has all the signatures reported together, unlike the other sources.

This curation is complete. Thank you.

**Comment by SvetlanaUP** [comment] 2024-07-15 19:33
https://bugsigdb.org/Study_924 reviewed.

**Closed by SvetlanaUP** 2024-07-15 19:33 UTC
Labels: second contribution, reviewed, needs 2nd review, outreachy may2024
