### ISSUE TITLE
Short chain fatty acids and gut microbiota differ between patients with Parkinson's disease and age-matched controls

### ISSUE THREAD

**Issue by Omabekee** [waldronlab/BugSigDBcuration#206] opened 2024-03-07 12:18 UTC
Short chain fatty acids and gut microbiota differ between patients
with Parkinson's disease and age-matched controls - Unger et al. - Parkinsonism & Related Disorders 
https://www.prd-journal.com/article/S1353-8020(16)30323-6/abstract

**Comment by Praiseagbetuyi** [comment] 2024-03-07 15:35
Kindly assign this paper to me for curation, @SvetlanaUP 

_Thank you._

**Comment by SvetlanaUP** [comment] 2024-03-07 15:58
@Praiseagbetuyi you are assigned to https://github.com/waldronlab/BugSigDBcuration/issues/202

**Comment by Omabekee** [comment] 2024-03-07 16:34
[Download article.pdf](https://github.com/waldronlab/BugSigDBcuration/file
[Supplemental fig 3.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527226/Supplemental.fig.3.pdf)
s/1452718
[Supplemental. fig 1.pdf
[Supplemental fig 2b.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527224/Supplemental.fig.2b.pdf)
](https://github.com/waldronlab/BugSigDBcuration/files/14527222/Supplemental.file.1.pdf)
[Supplemental fig 2a.pdf](https://github.com/waldronlab/BugSigDBcuration/files/14527223/Supplemental.fig.2.pdf)

8/Download.article.pdf)

**Comment by Ademolawe** [comment] 2024-03-07 16:46
Hello, can I curate this paper for my second curation?
Eniola Adebayo

**Comment by Ademolawe** [comment] 2024-03-10 19:43
Hello, this curation is ready for review https://bugsigdb.org/Study_944

Eniola Adebayo

**Comment by Peacesandy** [comment] 2024-03-21 03:22
Hi @Ademolawe this is a good curation attempt. However here are some few points to note ✍️

- The statistical test used is Kruskal-Wallis test, In the passage it was stated that the Kruskal-Wallis test was applied to analyze global differences between the three groups.  Mann-Whitney U test was used for post-hoc comparison. In order to control family-wise error rate caused by multiple comparison Bonferroni correction was carried out.
- The significance threshold is 0.01
- Control Young - CY and Parkinson's disease was used as groups for experiment 2 , you omitted signatures for the increased abundance.

*N/B* This study has been corrected and marked as reviewed. For ease you can go through the reviewed study to see the corrections I made.

**CURATION RESULT**

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 1
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (2 points): 1
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 0
14. All diversity measures identified (1 point): 1
15. Diversity results correctly entered as increased/decreased/unchanged (1 point): 1
16. All signature sources correctly identified (-1 for each error) (2 points): 2
17. Abundance direction correctly selected (1 point): 1
18. Members of Signatures identified correctly (2 points): 1
19. Correct use of NCBI taxonomy (2 points): 1

**Total (maximum 23 points): 19**

@SvetlanaUP https://bugsigdb.org/Study_944 Reviewed and corrected ✅

**Comment by Ademolawe** [comment] 2024-03-21 06:51
Good morning, thank you for the review.
I have an observation and question. From what we were taught on BugSigDB, the asterisk sign is used to connote significance. For example, from figure 1 there is no asterisk on some taxa when CY and PD group were compared. So is Bifidobacterium sp. significantly different between CY compared to PD group . Same question for Faecalibacterium prausnitzii and Prevotellaceae between CY and PD group, is it significantly different.
Thank you. @SvetlanaUP @Peacesandy @Folakunmi21

**Comment by Ademolawe** [comment] 2024-03-21 10:46
Hi @Peacesandy @SvetlanaUP 
I observed that I was scored 1 out of 2 for identified sequencing details. Please, can I get a clarification on it. You only made remark on the statistical details.
Thank you.

**Comment by Peacesandy** [comment] 2024-03-23 08:07
Hi @Ademolawe  please did you check the supplemental material while curating this study? Tho this study is kind of confusing, it is advisable that you also read the text describing the result to get a better understanding of the result interpretation. In the paper it was stated that *Prevotellaceae* (a bacterial family assigned to the phylum Bacteroidetes) were also descriptively reduced in PD patients compared to controls, descriptively not significantly, so it shouldn't be entered as a signature.

The paper also stated that *Faecalibacterium prausnitzii* (a bacterial species that belongs to the phylum Firmicutes) as well as *Lactobacillaceae* and *Enterococcaceae* (two bacterial families that belong to the phylum Firmicutes) were significantly reduced in the samples of PD patients compared to age-matched controls. Notice it stated age-matched controls which should include both CY and CM. But if you are going by the asterisks sign in the figure, *Faecalibacterium prausnitzii* should not be entered as significant in the CY group, but regardless it was significant in the PD group.

Secondly you were scored 1 out of 2 for identified sequencing details because, you entered Lactobacillus and Enterococcus, if you read the follow up text after the result, it was stated that, "*Lactobacillaceae* and *Enterococcaceae* (two bacterial families that belong to the phylum Firmicutes) were significantly reduced in the samples of PD patients compared to age-matched controls."In figure 1, *Lactobacilli* and *Enterococci* were written quite alright, but it can't be found on NCBI, since the paper stated *Lactobacillaceae* and *Enterococcaceae* in the text, that would have been a better option instead of *Lactobacillus* and *Enterococcus*. 

Please take out time to read the text describing any figure you are curating, it will give you a better understanding when interpreting the result.

**Comment by Peacesandy** [comment] 2024-05-07 08:54
@SvetlanaUP Reviewed and corrected

**Comment by SvetlanaUP** [comment] 2024-05-07 10:16
https://bugsigdb.org/Study_944 reviewed.

**Closed by SvetlanaUP** 2024-05-07 10:16 UTC
Labels: second contribution, reviewed, outreachy may2024
