### ISSUE TITLE
Microbiome analysis reveals gut microbiota alteration of early-weaned Yimeng black goats with the effect of milk replacer and age

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#392] opened 2024-05-08 09:23 UTC
Microbiome analysis reveals gut microbiota alteration of early-weaned Yimeng black goats with the effect of milk replacer and age

https://pubmed.ncbi.nlm.nih.gov/33789672/

**Comment by Buraah** [comment] 2024-05-15 13:51
Hello @SvetlanaUP 
Please I would love to be assigned to this.
Thank you.

**Comment by Buraah** [comment] 2024-05-15 14:55
Thank you @SvetlanaUP

**Comment by Buraah** [comment] 2024-05-31 12:13
Hello @SvetlanaUP , @Scholarpat 
I should have been done with this curation, but the figures pose a huge challenge for me.

This study has 14 experiments, 6 of which I have curated from the first figure showing differential abundance (figure 6). There are 8 more experiments to go, but the figure I will curate from is not visible. So currently I am at a roadblock with this study.

**Comment by SvetlanaUP** [comment] 2024-05-31 12:36
@Buraah What do you mean by not visible figure?

**Comment by Buraah** [comment] 2024-05-31 12:39
> @Buraah What do you mean by not visible figure?

The names of the microorganisms are blurry, it is difficult to figure them out. ( mostly figure 7).
I will share a screenshot of how it looks from my end.

**Comment by Scholarpat** [comment] 2024-05-31 12:42
It is also blurry from my end too @Buraah.
So sorry for the stress. Should have checked it out very well before creating the issue.

 I can't make out most of the signatures from the LeFse figure @SvetlanaUP .

**Comment by Buraah** [comment] 2024-05-31 12:44
![Uploading Screenshot (62).png…]()

**Comment by Buraah** [comment] 2024-05-31 12:46
> It is also blurry from my end too @Buraah. So sorry for the stress. Should have checked it out very well before creating the issue.
> 
> I can't make out most of the signatures from the LeFse figure @SvetlanaUP .

Yeah, and mostly the signatures in Figure 7. I could see the ones in Figure 6.

**Comment by SvetlanaUP** [comment] 2024-05-31 12:47
Ok, I understand it now. I will contact the authors and CC you both to the email.

**Comment by SvetlanaUP** [comment] 2024-06-17 08:25
@Scholarpat @Buraah after emailing the authors and a kind reminder for the email sent >10 days ago **we did not get any response from the authors**, we decide to proceed with curation based on what we have now "visible".

Please finalize curation with a note of poor quality of the figures as the challenge for this curation.

**Comment by Buraah** [comment] 2024-06-17 08:36
Okay @SvetlanaUP 
I'll finalize the curation and get back here when I'm done.

I might take a few days, I lost family last night. It's a long day for me.
Thank you

**Comment by SvetlanaUP** [comment] 2024-06-17 08:38
@Buraah sorry for your loss, and please take your time!

**Comment by Scholarpat** [comment] 2024-06-17 08:41
@Buraah so sorry for your loss

**Comment by Buraah** [comment] 2024-06-21 11:56
Hi @SvetlanaUP 
I have finalized this curation and it's ready for review.
Study link: https://bugsigdb.org/Study_1083

**Comment by SvetlanaUP** [comment] 2024-12-13 08:42
@IfeanyiSam https://github.com/IfeanyiSam could you please review this curation?

**Comment by IfeanyiSam** [comment] 2024-12-13 09:30
@SvetlanaUP I will get on this. Thank you

**Comment by Buraah** [comment] 2024-12-16 16:02
Hi @IfeanyiSam, Thank you!
I struggled a little bit with the signature names because they were blurry. Thank you so much for the corrections!🌷

1. Regarding alpha diversity, the study said that "Chao1, Simpson and Shannon indices did not change significantly."  However, the results in Fig. 2 showed some differences. For example, Chao1 is increased in B25.2 compared to B15.2(experiment 1). Judging by the bar graph, B25.2 is more than twice the size of B12.2.
So, while I curated based on the results, I'm very open to changing everything in the study to "Unchanged" if we're going just based on the text.

2. Thanks for the correction in Experiment 1!
 
4. Chloroplast and Unidentified chloroplast are organelles, so I didn't curate them initially. After seeing this, I  also checked the discussion page and saw that chloroplast was confirmed as _**Cynobacteriota**_. Thank you, this is fixed now.✨

**Comment by IfeanyiSam** [comment] 2024-12-16 16:29
@Buraah Thank you for acknowledging the changes. As for the alpha diversity, I think they should be reported as unchanged. The text suggests that and the figure itself doesn’t show any change (in my experience so far, if there’s a change, you’ll see horizontal lines or asterisks on the bars with significant changes).

**Comment by Buraah** [comment] 2024-12-16 17:55
Great!
All alpha diversity is now 'Unchanged'. I've reread the paper and compared it with a previously curated one. While the results show apparent differences, they are not **statistically** significant.

I believe the use of asterisks and horizontal lines is highly subjective to the author because not every author uses them to indicate significance.
For example, in this already curated study: https://journals.asm.org/doi/10.1128/aem.02479-18
The results are significant, but no asterisks or horizontal lines indicate this. Instead, the authors used a box plot to show the differences.

Hi @SvetlanaUP, all corrections have been made.
Waiting for your approval @IfeanyiSam.
Thank you!

**Comment by IfeanyiSam** [comment] 2024-12-16 18:19
@Buraah Welldone.
In the paper, note that words like “significantly higher” and “varied significantly” were used here which suggest there was change in the alpha diversity. 
thanks for sharing.

@SvetlanaUP this study is complete now.

**Comment by IfeanyiSam** [comment] 2024-12-16 19:46
@SvetlanaUP This review is complete.

**Comment by SvetlanaUP** [comment] 2024-12-17 08:34
https://bugsigdb.org/Study_1083 reviewed.

**Closed by SvetlanaUP** 2024-12-17 08:34 UTC
Labels: paper to curate, assigned, needs review, outreachy may2024
