### ISSUE TITLE
 Drinking alcohol is associated with variation in the human oral microbiome in a large study of American adults

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#36] opened 2023-03-12 15:16 UTC
https://pubmed.ncbi.nlm.nih.gov/29685174/

**Comment by Bahati308** [comment] 2023-03-12 18:41
@lwaldron, i can take over this please. Can i go on

**Comment by Bahati308** [comment] 2023-03-12 21:00
@lwaldron , please review this and kindly advise 
https://bugsigdb.org/Study_739

**Comment by lwaldron** [comment] 2023-03-13 10:23
You need the full paper to complete curation, sorry it was behind a paywall, see attached for the full PDF. One quick thing I noticed, you should enter the PMID with the study and allow the wiki to auto-fill study information like abstract. 
[drinking-alcohol-is-associated-with-variation-in-the-human-oral--2018.pdf](https://github.com/waldronlab/BugSigDBcuration/files/10956226/drinking-alcohol-is-associated-with-variation-in-the-human-oral--2018.pdf)

**Comment by lwaldron** [comment] 2023-03-13 10:24
Removing the "needs review" label until you finish entering any signatures from the full paper.

**Comment by Bahati308** [comment] 2023-03-13 19:33
@lwaldron thanks a lot , so can i please redo it . will be updating you

**Comment by Bahati308** [comment] 2023-03-13 19:34
i also request that the issue is assigned to me please

**Comment by Bahati308** [comment] 2023-03-13 20:03
@cmirzayi thanks a lot please

**Comment by Bahati308** [comment] 2023-03-14 03:31
@cmirzayi , @lwaldron  kindly look at my edits, and some advise please. Tanks

https://bugsigdb.org/Study_739

**Comment by Bahati308** [comment] 2023-03-14 03:39
made some mistake which I am working on please, i have realized it . So sorry

**Comment by cmirzayi** [comment] 2023-03-14 13:21
@Bahati308 Please let us know when it's ready for review. Mistakes happen so don't worry about it!

**Comment by Bahati308** [comment] 2023-03-15 01:08
@cmirzayi , @lwaldron it is ready for review now, thanks a lot for the encouragement

**Comment by Bahati308** [comment] 2023-03-15 01:09
below is the link


https://bugsigdb.org/Study_751

**Comment by ftzohra22** [comment] 2023-03-25 10:39
@Bahati308 You did a great job with this curation. There were a few errors (please see details below). Also remember to only curate results that is significant. For figure 3 and 4, only taxa with an asterisk (*) are considered significant. Please revise the feedback and make the necessary corrections. Good effort!

1. All elements marked "Needs review" (none "Incomplete") (1 point): 1
2. Correct study design (1 point): 0 (this is a cross sectional study)
3. Entered all relevant experiments and no irrelevant experiments (1 point): 1
4. Body site correctly identified (i.e. does not include multiple sites) (1 point): 1 
5. Condition entered according to contrast (correct EFO ontology) (1 point): 1 
6. Contrast groups correctly identified (1 point): 1
7. Groups correctly labeled as 1 and 0 (1=cases, 0=controls) (1 point): 1
8. Antibiotic exclusion correctly identified (1 point): 1
9. Correctly identified sequencing details (1 point for sequencing type and variable region, 1 point for sequencing platform) (2 points): 1 (variable region missing from experiment 2, 3, 4 and 5)
10. Identified correct statistical test (1 point): 1
11. Identified MHT correction (1 point): 1
12. Correctly recorded matched on factors (1 point): 1
13. Entered correct number of statistical tests per experiment (1 point): 1 
14. All diversity measures identified (1 point):1
15. Diversity results correctly entered as increased/ decreased/ unchanged (1 point): 1 
16. All signature sources correctly identified  (-1 for each error)  (2 points): 1 
17. Abundance direction correctly selected (1 point): 1 
18. Members of Signatures identified correctly (1 point for single small error, 0 points for anything more. Incorrect means missing or extraneous taxon) (2 points): 1 (we only curate siginficant results. for all the results in figure 3 and 4 anything marked with a "*" is sigificant. 
19. Correct use of NCBI taxonomy (don't deduct if can't easily find correct taxon in NCBI taxonomy database. 1 for one error, 0 for multiple errors) (2 points): 2

Total (maximum 24 points): 19

**Comment by Bahati308** [comment] 2023-03-25 20:09
thanks alot for the feed back. i promise to improve. thanks

**Comment by kahvecirem** [comment] 2023-03-31 21:56
Hi this article have two study page in system
https://bugsigdb.org/Study_660
https://bugsigdb.org/Study_751

**Comment by Susu-spec** [comment] 2023-04-01 19:27
Outstanding issues have been fixed:
https://bugsigdb.org/Study_751

**Comment by Bahati308** [comment] 2023-04-02 16:32
it is fine, thanks

**Comment by ftzohra22** [comment] 2023-04-03 20:36
@Bahati308 @Susu-spec Thank you both for contributing on this paper together and making the corrections.

**Closed** 2023-04-03 21:08 UTC
Labels: second contribution, outreachy may23, paper to curate, assigned, reviewed, outstanding issues
