### ISSUE TITLE
Mismatched experiments for Study 340

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BugSigDBcuration#23] opened 2023-03-11 12:23 UTC
The experiments of https://bugsigdb.org/Study_340 are clearly from a different study. Can someone figure out which study these experiments actually belong to?

Smaller point, I would say this is a case-control study (as opposed to observational, not case-control), since participants were selected on the basis of disease status.

**Comment by cmirzayi** [comment] 2023-03-11 17:49
https://bugsigdb.org/Study_95 I think.

**Comment by ftzohra22** [comment] 2023-03-12 11:14
I think this happened when I was deleting a duplicate of https://bugsigdb.org/Study_95. The experiments might not have gotten deleted and somehow got mismatched with https://bugsigdb.org/Study_340 ( PMID: 33653942) which was being created at the same time.

**Comment by cmirzayi** [comment] 2023-05-10 18:19
I think this has been resolved in curation, even if the related issue is still open for the devs so we can close.

**Closed by cmirzayi** 2023-05-10 18:19 UTC
