### ISSUE TITLE
Genomic analysis identifies association of Fusobacterium with colorectal carcinoma

### ISSUE THREAD

**Issue by Peacesandy** [waldronlab/BugSigDBcuration#289] opened 2024-03-14 11:08 UTC
Genomic analysis identifies association of Fusobacterium with colorectal carcinoma - Aleksandar D Kostic et al. - Genome Res 

https://pubmed.ncbi.nlm.nih.gov/22009990/

**Comment by kingyy200** [comment] 2024-03-14 17:14
Hi @SvetlanaUP. Please assign me this paper for curation.

**Comment by MyleeeA** [comment] 2024-03-30 11:50
Hi @kingyy200 can we collaborate on this if you are not done with it?

**Comment by SvetlanaUP** [comment] 2024-04-05 08:58
Assigned to @MyleeeA 
Please continue curating https://bugsigdb.org/Study_878

**Comment by MyleeeA** [comment] 2024-04-05 11:13
Thank you 🙏🏾 @SvetlanaUP

**Comment by FaithAlexander** [comment] 2024-04-07 20:46
Hello @MyleeeA how is your curation going? I would love to know if you are open to collaboration because I would love to collaborate with you on this curation if that is Okay. I would be expecting your response. 

Thanks.

**Comment by MyleeeA** [comment] 2024-04-08 15:17
Sure @FaithAlexander i still have a few things I haven’t figured out yet you could help 


Link to curation  
https://bugsigdb.org/Study_878

**Comment by MyleeeA** [comment] 2024-04-09 09:39
@FaithAlexander I believe you haven’t gotten my response agreeing to the collaboration, I’ve been able to complete the curation 
Thank you for offering to help

@SvetlanaUP this curation is ready for review 
https://bugsigdb.org/Study_878

**Comment by FaithAlexander** [comment] 2024-04-09 10:50
@MyleeeA yes I didn't get your response until now. So sorry that I wasn't able to help but I am glad that you have been able to figure it out. 

Thank you for agreeing to let me collaborate with you.

**Comment by Scholarpat** [comment] 2024-06-26 11:50
Hi @MyleeeA,

This is a great curation! 👏

I've reviewed and confirmed all the details curated.

I made a slight adjustment group 0 name, changing it from 'Normal colonic tissue' to '**Adjacent** normal colonic tissue' to quickly indicate that both samples were obtained from the same participant.

This curation is complete. @SvetlanaUP, thank you!

**Comment by SvetlanaUP** [comment] 2024-06-26 12:20
https://bugsigdb.org/Study_878 reviewed.

**Closed by SvetlanaUP** 2024-06-26 12:20 UTC
Labels: second contribution, paper to curate, assigned, needs review, outreachy may2024

**Comment by MyleeeA** [comment] 2024-06-27 12:46
Thank you @Scholarpat and well done on the work you are doing 👏🏾
