### ISSUE TITLE
Gut metagenomes of Asian octogenarians reveal metabolic potential expansion and distinct microbial species associated with aging phenotypes

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#500] opened 2024-09-30 14:19 UTC
Gut metagenomes of Asian octogenarians reveal metabolic potential expansion and distinct microbial species associated with aging phenotypes – Aarthi Ravikrishnan – Nature Communications 
https://www.nature.com/articles/s41467-024-52097-9

Summary thread by the author: https://twitter.com/aarthiravikrish/status/1833348458104946692

**Comment by MaryAgekameh** [comment] 2024-10-02 20:42
@SvetlanaUP please can you assign me to this paper?

**Comment by MaryAgekameh** [comment] 2024-10-03 07:11
Mary Agekameh 

I'd like to claim this issue for curation

**Comment by MyleeeA** [comment] 2024-10-09 15:16
Hi @MaryAgekameh 

How’s your curation coming along?

I’m open to help if you are experiencing any blockers 
Thank you 🙏🏾

**Comment by MaryAgekameh** [comment] 2024-10-10 08:10
Hello @MyleeeA 

Thank you for reaching out 
Yes I'm having some difficulties

**Comment by MyleeeA** [comment] 2024-10-10 08:11
Okay 

Have you started the curation?
In what way are you experiencing difficulties?

**Comment by MaryAgekameh** [comment] 2024-10-10 08:19
My internet was bad when Chloe explained how to begin in the meeting last week

That's my problem 
I don't know how or what to start with

**Comment by SvetlanaUP** [comment] 2024-10-10 08:21
@MaryAgekameh @MyleeeA, you can continue your discussion in Slack DM. Enjoy your team work!

**Comment by MaryAgekameh** [comment] 2024-10-10 08:23
Okay 
Thank you @SvetlanaUP

**Comment by MyleeeA** [comment] 2024-10-10 08:44
Thank you @SvetlanaUP

**Comment by MaryAgekameh** [comment] 2024-10-28 19:27
@SvetlanaUP The curation is ready for review
https://bugsigdb.org/Study_1149

**Comment by Omabekee** [comment] 2024-11-14 14:02
Wow, I’m impressed! This is such a great curation, especially given the scope of this study. Great teamwork here! @MyleeeA and @MaryAgekameh. However, given the scale of the study, it looks like a few taxa may have been missed in some experiments. Please see my notes below and update as needed. Well done!

- Lactobacillus mucosae is listed on the NCBI Taxonomy Browser as 97478.
- full meaning of “SPMP” should be fixed in group descriptions
- Experiment 12 / sig. 2 should include 25 taxa, I counted 23.
- Please correct the data transformation for Experiment 13.
- For Experiment 13 / sig. 1, there should be 12 taxa; it looks like Alistipes shahii was included by mistake.
- The sources for Experiments 13 and 14 should reference Supplementary Figure 3, not File 3.
- In Experiment 14 / sig. 2, Eubacterium hallii and Coprococcus comes are missing, while Ruminococcus bromii should be excluded.
- The source description for Experiment 16 / sig. 1 could use more detail.
- Experiment 17 is missing a data transformation.

| Item | Description                                                          | max | points |
|------|----------------------------------------------------------------------|-----|--------|
| 1    | All elements marked "Needs review" (none "Incomplete")               | 1   |  1      |
| 2    | Correct study design                                                 | 1   |     1   |
| 3    | Entered all relevant experiments and no irrelevant experiments       | 1   |   1     |
| 4    | Body site correctly identified (i.e. does not include multiple sites)| 1   |   1     |
| 5    | Condition entered according to contrast (correct EFO ontology)       | 1   |    1    |
| 6    | Contrast groups correctly identified                                 | 1   |   1     |
| 7    | Groups correctly labeled as 1 and 0 (1=cases, 0=controls)            | 1   |   1     |
| 8    | Antibiotic exclusion correctly identified                            | 1   |   1     |
| 9    | Correctly identified sequencing details                              | 2   |  1      |
| 10   | Identified correct statistical test                                  | 1   |    1    |
| 11   | Identified MHT correction                                            | 1   |    1    |
| 12   | Correctly recorded matched on factors                                | 1   |     1   |
| 13   | Entered correct number of statistical tests per experiment           | 1   |   1     |
| 14   | All diversity measures identified                                    | 1   |    1    |
| 15   | Diversity results correctly entered as increased/decreased/unchanged | 1   |  1      |
| 16   | All signature sources correctly identified (-1 for each error)       | 2   |   1     |
| 17   | Abundance direction correctly selected                               | 1   |     1   |
| 18   | Members of Signatures identified correctly                           | 2   |    1    |
| 19   | Correct use of NCBI taxonomy                                         | 2   |   1.5     |
|      | TOTAL                                                                | 23  |   19.5     |

**Comment by MaryAgekameh** [comment] 2024-11-14 14:50
Thank you so much for your kind words! @Omabekee. We will review and update as needed

**Comment by MyleeeA** [comment] 2024-11-15 05:19
Thank you @Omabekee we would effect the corrections

**Comment by MyleeeA** [comment] 2024-11-19 09:00
Hi @Omabekee 
Thank you again for the review 
This curation is ready for a second review 

All corrections have been effected asides writing full meaning of “SPMP” because the paper didn’t state the meaning 

Thank you 😊

**Comment by Omabekee** [comment] 2024-11-20 11:38
Thank you, all corrections confirmed. 

Full meaning of SPMP is Singapore Platinum Metagenomes Project, confirmed from online sources (https://www.nature.com/articles/s41467-022-33782-z). Kindly correct and revert.

**Comment by MyleeeA** [comment] 2024-11-20 13:37
Noted, Thank you for the information on that

We will get to it immediately @Omabekee

**Comment by MyleeeA** [comment] 2024-11-22 16:42
Hi @Omabekee @SvetlanaUP 
Corrections have been effected 

Thank you again

**Comment by Omabekee** [comment] 2024-11-22 17:02
Great! @SvetlanaUP, review of Study 1149 complete. ✅

**Closed** 2024-11-22 17:12 UTC
Labels: second contribution, paper to curate, assigned, reviewed, outreachy dec2024
