### ISSUE TITLE
The long-term gut bacterial signature of a wild primate is associated with a timing effect of pre- and postnatal maternal glucocorticoid levels

### ISSUE THREAD

**Issue by SvetlanaUP** [waldronlab/BugSigDBcuration#173] opened 2023-12-11 12:53 UTC
The long-term gut bacterial signature of a wild primate is associated with a timing effect of pre- and postnatal maternal glucocorticoid levels – Simone Anzà et al. – Microbiome 2023
https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-023-01596-w

**Comment by runananya** [comment] 2024-03-05 14:01
hey , could i be assigned to this paper!

**Comment by runananya** [comment] 2024-03-05 14:54
> I just assigned this study to you @runananya

thank youuu @Peacesandy

**Comment by SvetlanaUP** [comment] 2024-03-18 20:50
@Analyst-Joan @ikehdarlington, could you please help here out?
https://bugsigdb.org/Study_911

**Comment by ikehdarlington** [comment] 2024-03-18 21:42
Sure @SvetlanaUP

**Comment by Analyst-Joan** [comment] 2024-03-19 16:24
Okay @SvetlanaUP

**Comment by ikehdarlington** [comment] 2024-03-19 17:15
> Alright @SvetlanaUP. 
> 
> 
> 
> @ikehdarlington do I still join you on this? I see you're already on it

@Analyst-Joan we can work on it together. It looks stubborn but we can tame it together and squeeze out the needed juice for BugSigDB. I used today to study the article. Maybe that's why our mentor assigned it to both of us. Study it and let's talk.

**Comment by Analyst-Joan** [comment] 2024-03-19 17:17
Alright @ikehdarlington

**Comment by Analyst-Joan** [comment] 2024-03-20 11:35
@ikehdarlington  
Observations so far:
**Statistical test** - _ANCOM_
**MHT correction** - _Yes_
**Nearest EFO Condition** should be _**response to glucocorticoid**_, not _gut microbiome measurement_

**Comment by ikehdarlington** [comment] 2024-03-20 12:02
@Analyst-Joan It's Linear Regression,

"The absolute abundance data were modeled by ANCOM-BC using a linear regression framework" - Page 6 of 26.
![image](https://github.com/waldronlab/BugSigDBcuration/assets/154360284/5801601a-9c47-4879-8b02-0e4c298d906a)

**Comment by Analyst-Joan** [comment] 2024-03-20 12:10
Yea @ikehdarlington  , a further study of the paper for the condition now have me between **_seasonal gut microbiome measurement_** and **_response to glucocorticoid_** 🤔 

Well, **_Experiments are defined by the contrasts made_** and The _**Condition is what is being contrasted in the experiment.**_ Once we decipher the experiments carried out, we'd sure have more insights on which to use. 😄

**Comment by ikehdarlington** [comment] 2024-03-20 12:13
> Yea @ikehdarlington , a further study of the paper for the condition now have me between **_seasonal gut microbiome measurement_** and **_response to glucocorticoid_** 🤔
> 
> Well, **_Experiments are defined by the contrasts made_** and The _**Condition is what is being contrasted in the experiment.**_ Once we decipher the experiments carried out, we'd sure have more insights on which to use. 😄

I'll suggest we put all that applies, since we ain't limited to one or two

**Comment by Analyst-Joan** [comment] 2024-03-20 15:20
@ikehdarlington The statistical test selected is for the experiments, so which experiment(s) are you suggesting was used with linear regression?

**Comment by ikehdarlington** [comment] 2024-03-20 15:53
> @ikehdarlington The statistical test selected is for each experiments, so which experiment(s) are you suggesting linear regression was used?
> 
> 
> 
> 

@Analyst-Joan I'm opined that the main experiments to be curated are (putting in simple terms) the effects or GC levels on the relative abundances, from early pre-natal to late post-natal for rich season and all of these are shown in Fig 4. 

We'll ignore lean season because according to Table 2 the relative abundances are not too significant. 

I have started for Experiment 1(early pre-natal GC) Fig 4A, you can start for Experiment 2. Refer to Fig 4B. 

As for the statistical tests, ANCOM-BC combines bias correction, linear regression (LR), and compositional data analysis to enhance the accuracy and reliability of microbiome differential abundance analysis, so we're going to list both ANCOM-BC and LR.

**Comment by Analyst-Joan** [comment] 2024-03-20 16:02
@ikehdarlington  The statistical test used is ANCOM-BC (Analysis of Compositions with Bias Correction). ANCOM-BC is a method specifically designed for analyzing compositional data, which are datasets where the relative proportions of different components are important rather than their absolute values.

ANCOM-BC employs a linear regression framework to model absolute abundance data while considering the unknown sampling fractions and correcting biases induced by differences among samples. It provides statistically valid tests with appropriate p-values, confidence intervals for the differential abundance of each taxon, and controls the false discovery rate to maintain adequate power while simplifying the computational implementation.

The ANCOM-BC analyses were conducted separately at the phylum, family, and genus levels for both the rich and lean seasons. This separation was necessary because ANCOM-BC does not allow for longitudinal analysis, hence requiring separate analyses for different seasons or time points.

**Comment by Analyst-Joan** [comment] 2024-03-20 16:06
I'm putting my curation in a file format first, which i hope to share with you when done and we discuss before I curate them into #BugSigDB.  

We can also post questions in the slack general group to glean from others insights. 🙏

**Comment by SvetlanaUP** [comment] 2024-03-20 17:02
@Analyst-Joan @ikehdarlington please continue discussion in the Slack #bugsigdb so others could profit from your discussion. Thanks!

**Comment by Analyst-Joan** [comment] 2024-03-20 17:46
Alright @SvetlanaUP

**Comment by ikehdarlington** [comment] 2024-03-28 07:54
@SvetlanaUP Good day. the curation https://bugsigdb.org/Study_911 is ready for review.

@Analyst-Joan ! It was nice working with you on this one.

**Comment by SvetlanaUP** [comment] 2024-04-11 13:28
@Analyst-Joan @ikehdarlington @runananya well done!

You have greetings from the author of this study:

_Thank you for putting this together, it is such an effort to standardize this info for others, kudos to the team that did a great job!

I've found some minor info you may want to update: 
- Perhaps it is a constraint you have in the way of coding data into the portal but the ANCOM-BC approach was performed with AGE as covariate, not categorical variable (like the Alpha diversity analyses), the plot Fig 4A shows the +-1SD against the mean just to visualize results. 
- For the **alpha diversity analyses** we ran GLMMs with a full-null model comparison on several metrics: pure richness-based estimators (ObservedASVs, ACE; Model 1a-1b), Faith’s phylogenetic diversity (PD) as phylogenetic richness estimator (Model 1c), and richness-evenness estimators (i.e., Shannon-Weaver, Inverse Simpson: Model 1d-1e). 
- Concerning the experiment 12, the group names **MOT, MST, SST** are just group names for my team, they are not related to any maternal or social characteristic of the subject, it could be group A, B and C...perhaps you could write just the group name? It's up to you. 

Other than that, thank you so much to the team for investing in this, I am sure it was a hard job.

Cheers,
Simo_

| Item | Description | max | points |
|---|---|---|---|
| 1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1 |
| 2 | Correct study design | 1 | 1 |
| 3 | Entered all relevant experiments and no irrelevant experiments | 1 | 1 |
| 4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1 |
| 5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1 |
| 6 | Contrast groups correctly identified | 1 |1 |
| 7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1 |
| 8 | Antibiotic exclusion correctly identified | 1 | 1 |
| 9 | Correctly identified sequencing details | 2 | 2 |
| 10 | Identified correct statistical test | 1 | 1 |
| 11 | Identified MHT correction | 1 | 1 |
| 12 | Correctly recorded matched on factors | 1 | 1 |
| 13 | Entered correct number of statistical tests per experiment | 1 | 1 |
| 14 | All diversity measures identified | 1 | 1 |
| 15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1 |
| 16 | All signature sources correctly identified (-1 for each error) | 2 | 2 |
| 17 | Abundance direction correctly selected | 1 | 1 |
| 18 | Members of signatures identified correctly | 2 | 2 |
| 19 | Correct use of NCBI taxonomy | 2 | 2 |
|  | TOTAL | 23 | 23 |

**Comment by Analyst-Joan** [comment] 2024-04-11 14:15
Thanks for the update @SvetlanaUP. 

Oh, It's really heartwarming hearing from the author 😍 .

In the coming days, as I finish current curations at hand, I hope to review the paper in the light of the new info presented by the author.

Thanks again for all you do 🌷.

**Comment by SvetlanaUP** [comment] 2024-04-11 19:22
@Analyst-Joan take your time, once corrections done, please do let me know. Thank you.

**Comment by ikehdarlington** [comment] 2024-04-11 19:37
@SvetlanaUP This is really heartwarming to know, that the author reached out. @Analyst-Joan @runananya Congrats to us. 
@Analyst-Joan, I left a message for you on slack. Let's plan on how to effect the comments from the review.

**Comment by SvetlanaUP** [comment] 2024-04-22 08:51
@Analyst-Joan @ikehdarlington just to check if corrections of this curation are finalized?

**Comment by ikehdarlington** [comment] 2024-04-22 09:26
@SvetlanaUP We are still working on it. Hoping to finish today, latest tomorrow.

**Comment by Analyst-Joan** [comment] 2024-04-22 09:53
Good morning, @SvetlanaUP working at aligning the Author's feedback with the curation. 

For the 3rd point, They stated that _**MOT, MST, SST are just group names by the research team, unrelated to any maternal or social characteristic of the subject**_. 
However, BugSigDB has group definition option - So, we'll need clarity from the author on what the differentiating criteria were for the grouping? like on what basis was a subject/group of subjects classified into MOT and the other MST or SST? This will help the info on BugSigDB less vague to anyone getting to that part of the study on the database.

Could you help us reach out to Author, Please?

**Comment by SvetlanaUP** [comment] 2024-04-22 11:36
@Analyst-Joan we are usually not contacting the authors of the paper for its interpretation. However, the author spontaneously contacted us and provided additional information already. Please do include what you have right now.

**Comment by Analyst-Joan** [comment] 2024-04-23 16:10
@SvetlanaUP All feasible corrections have now been made.
Thanks.

cc: @ikehdarlington

**Closed** 2024-09-13 10:18 UTC
Labels: second contribution, paper to curate, assigned, needs 2nd review, outreachy may2024

**Comment by Shulamite54** [comment] 2025-04-07 12:19
Hi, @SvetlanaUP the study information of the article is still marked incomplete, but the paper has been reviewed, can I change it? Thank you. Can I also be assigned to work on some of the missing taxa in the study

**Comment by SvetlanaUP** [comment] 2025-04-07 13:33
Please do not change anything for now, @Shulamite54 

Recently, our curators reported 
https://bugsigdb.org/30738924
https://bugsigdb.org/30231060
https://bugsigdb.org/37501202
as reviewed but still marked incomplete. @cmirzayi could you please check them out? Maybe I missed the reason why we some reviewed studies left incomplete.

**Comment by Shulamite54** [comment] 2025-04-07 13:39
Okay, @Svetlana.

I also saw this study (https://bugsigdb.org/0312606) (Metabolic
requirements for anaerobic active Cl and Na transport in the bullfrog
cornea) and I have searched for it in Github issues with the title, but I
can't find it.


Orakwe, Oluomachi Precious
Virtual assistant and Email Manager.

LinkedIn <https://www.linkedin.com/in/preciousorakwe/>
