### ISSUE TITLE
Gestational diabetes is associated with change in the gut microbiota composition in third trimester of pregnancy and postpartum

### ISSUE THREAD

**Issue by Scholarpat** [waldronlab/BugSigDBcuration#469] opened 2024-08-09 13:01 UTC
Gestational diabetes is associated with change in the gut microbiota composition in third trimester of pregnancy and postpartum - Mie Korslund Wiinblad Crusell – Microbiome

https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-018-0472-x

**Comment by Onyin-o** [comment] 2024-10-03 10:20
Hi @SvetlanaUP i’d like to claim this issue for curation. Thank you

**Comment by Rahila-me** [comment] 2024-10-12 10:53
Good morning @Onyin-o @SvetlanaUP , Onyin please I am open for collaboration i just wanted to know if you need help to finish up this paper. Waiting for your reply.. Thank you

**Comment by Rahila-me** [comment] 2024-10-15 20:32
@SvetlanaUP @Onyin-o I have looked up this paper in bugsigdb and it shows it has not be created in the wiki, Should i still wait for the original owner to start before offering help @SvetlanaUP

**Comment by SvetlanaUP** [comment] 2024-10-16 07:41
@Rahila-me go ahead with curation of this paper, thanks!

**Comment by Rahila-me** [comment] 2024-10-16 09:35
@SvetlanaUP okay thank you

**Comment by MyleeeA** [comment] 2024-10-19 23:24
Hi @Rahila-me 

I have completed my second contribution and I am currently awaiting grading

I am available to collaborate with you on this, if that is okay
Thank you 🙏🏾

**Comment by Rahila-me** [comment] 2024-10-20 15:19
@MyleeeA Chia i am just seeing this now, and i have finished the curation.  Thanks for reaching out

**Comment by MyleeeA** [comment] 2024-10-20 15:50
That sounds great @Rahila-me 

Well done on your curation 👏🏾
Is this your second contribution?
Do you need peer review on it?

**Comment by Rahila-me** [comment] 2024-10-20 17:43
@MyleeeA No, The initial owner did not curate it.

**Comment by Rahila-me** [comment] 2024-10-20 17:44
@SvetlanaUP Good evening, This paper is ready for a review:
https://bugsigdb.org/Study_1169

**Comment by MyleeeA** [comment] 2024-10-20 18:50
Oh Yes

I’ve read the previous messages and I see that
Well done again 👏🏾

**Comment by SvetlanaUP** [comment] 2024-10-20 19:19
https://bugsigdb.org/Study_1169 ready fire review.

**Comment by Buraah** [comment] 2024-11-05 09:59
Hi @SvetlanaUP,
I want to review this.

**Comment by Buraah** [comment] 2024-11-07 14:04
Hi @Rahila-me,
Thank you for doing a good work.
Here are a few things I noted:
1. The data transformation for 'Wald test' is 'Raw counts'. This is because it is a negative binomial test, just like DESeq2.
2. The group 1 definitions for experiments 7, 8, 9 and 10 describe the signature source instead of defining the group. 
3. There's a signature 3 under experiment 9. Please ask for it to be deleted.
4. Experiments 11 & 12 are a duplicate of 1 & 2.
5. The Group 0 sample size for experiment 1 is 157 from the paper.
You can make corrections and ask for a final review. Thank you.
Overall, this is a great curation. Well done!

**Curation results:**
S/N | Criteria | Total Points | Points Earned
-- | -- | -- | --
1 | All elements marked "Needs review" (none "Incomplete") | 1 | 1
2 | Correct study design | 1 | 1
3 | Entered all relevant experiments and no irrelevant experiments | 1 | 0.5
4 | Body site correctly identified (i.e. does not include multiple sites) | 1 | 1
5 | Condition entered according to contrast (correct EFO ontology) | 1 | 1
6 | Contrast groups correctly identified | 1 | 0.5
7 | Groups correctly labeled as 1 and 0 (1=cases, 0=controls) | 1 | 1
8 | Antibiotic exclusion correctly identified | 1 | 1
9 | Correctly identified sequencing details | 2 | 2
10 | Identified correct statistical test | 1 | 1
11 | Identified MHT correction | 1 | 1
12 | Correctly recorded matched on factors | 1 | 1
13 | Entered correct number of statistical tests per experiment | 1 | 1
14 | All diversity measures identified | 1 | 1
15 | Diversity results correctly entered as increased/decreased/unchanged | 1 | 1
16 | All signature sources correctly identified (-1 for each error) | 2 | 1
17 | Abundance direction correctly selected | 1 | 1
18 | Members of signatures identified correctly | 2 | 2
19 | Correct use of NCBI taxonomy | 2 | 2
  | TOTAL | 23 | 22


</body>
</html>

Reviewed @SvetlanaUP

**Comment by Rahila-me** [comment] 2024-11-07 19:14
@Buraah Thank you for the review. I will make the necessary correction.

**Comment by Rahila-me** [comment] 2024-11-07 20:41
@Buraah @SvetlanaUP I have made the correction pointed out, so please raising it up again for a final review.

**Comment by Buraah** [comment] 2024-11-08 09:45
Hi @SvetlanaUP,
The second review is done.

Thank you @Rahila-me

**Closed** 2024-11-08 11:09 UTC
Labels: second contribution, paper to curate, assigned, reviewed, outreachy dec2024
